name: beacon_broadcast_example
description: Demonstrates how to use the beacon_broadcast plugin.
version: 0.3.2
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  beacon_broadcast:
    path: ../

flutter:
  uses-material-design: true