name: beacon_broadcast_example
description: Demonstrates how to use the beacon_broadcast plugin.
version: 0.3.4
publish_to: 'none'

environment:
  sdk: '>=3.3.5 <4.0.0'
  flutter: '>=3.24.5'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  beacon_broadcast:
    path: ../

flutter:
  uses-material-design: true