name: beacon_broadcast
description: A Flutter plugin for turning your device into a beacon. Plugin uses AltBeacon library for Android and
  CoreLocation for iOS.
version: 0.3.4+1
repository: https://github.com/thorito/beacon_broadcast.git
issue_tracker: https://github.com/thorito/beacon_broadcast/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: '>=3.3.5 <4.0.0'
  flutter: '>=3.24.1'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.19.1
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  material_color_utilities: ^0.12.0
  string_scanner: ^1.4.1

flutter:
  plugin:
    platforms:
      android:
        package: pl.pszklarska.beaconbroadcast
        pluginClass: BeaconBroadcastPlugin
      ios:
        pluginClass: BeaconBroadcastPlugin